"""Initial migration

Revision ID: 04f6e9836884
Revises: 
Create Date: 2026-04-09 23:11:24.736104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04f6e9836884"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_histories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("stock_code", sa.String(length=16), nullable=False),
        sa.Column("stock_name", sa.String(length=64), nullable=True),
        sa.Column("analysis_type", sa.String(length=16), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("fundamental_score", sa.Float(), nullable=True),
        sa.Column("technical_score", sa.Float(), nullable=True),
        sa.Column("recommendation", sa.String(length=16), nullable=False),
        sa.Column("analysis_result", sa.Text(), nullable=False),
        sa.Column("analysis_duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_histories_created_at"),
        "analysis_histories",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_histories_stock_code"),
        "analysis_histories",
        ["stock_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_histories_user_id"),
        "analysis_histories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("openai_api_key", sa.Text(), nullable=True),
        sa.Column("openai_base_url", sa.String(length=256), nullable=True),
        sa.Column("openai_model", sa.String(length=64), nullable=True),
        sa.Column("anthropic_api_key", sa.Text(), nullable=True),
        sa.Column("anthropic_model", sa.String(length=64), nullable=True),
        sa.Column("default_analysis_type", sa.String(length=16), nullable=False),
        sa.Column("default_days", sa.Integer(), nullable=False),
        sa.Column("feishu_webhook_url", sa.String(length=256), nullable=True),
        sa.Column("feishu_push_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_configs_user_id"), "user_configs", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_configs_user_id"), table_name="user_configs")
    op.drop_table("user_configs")
    op.drop_index(
        op.f("ix_analysis_histories_user_id"), table_name="analysis_histories"
    )
    op.drop_index(
        op.f("ix_analysis_histories_stock_code"), table_name="analysis_histories"
    )
    op.drop_index(
        op.f("ix_analysis_histories_created_at"), table_name="analysis_histories"
    )
    op.drop_table("analysis_histories")
    # ### end Alembic commands ###
